import { ref } from 'vue'
import { faIceCream, faLeaf, faBowlRice } from '@fortawesome/free-solid-svg-icons'

export const products = ref([
  // PICOLÉ DE LEITE
  {
    id: 32,
    name: 'Açaí',
    category: 'picole-leite',
    subtitle: 'Picolé cremoso de Açaí com Leite',
    description:
      'A energia do açaí em forma de picolé! Uma combinação cremosa e irresistível que une o sabor marcante do açaí da Amazônia com a suavidade do leite, criando uma experiência única e deliciosa.',
    type: 'image',
    src: '/images/picole-leite/acai.png',
    images: ['/images/picole-leite/acai.png'],
    ingredients: [
      'Polpa de açaí',
      'Água',
      'Açúcar',
      'Leite em pó',
      'Xarope de guaraná',
      'Estabilizantes',
    ],
    nutrition: {
      Porção: '65g (1 unidade)',
      'Valor Energético': '110 kcal',
      Carboidratos: '18g',
      Proteínas: '1.5g',
      'Gorduras Totais': '4g',
    },
    allergens: ['Contém leite.', 'Não contém glúten.'],
  },
  {
    id: 34,
    name: 'Abacaxi Suíço',
    category: 'picole-leite',
    subtitle: 'Picolé de Abacaxi com Leite Condensado',
    description:
      'A combinação perfeita entre a acidez do abacaxi e a doçura cremosa do leite condensado. Um picolé refrescante com um toque especial de sobremesa.',
    type: 'image',
    src: '/images/picole-leite/abacaxisuico.png',
    images: ['/images/picole-leite/abacaxisuico.png'],
    ingredients: [
      'Água',
      'Leite condensado',
      'Polpa de abacaxi',
      'Leite em pó',
      'Açúcar',
      'Estabilizantes',
    ],
    nutrition: {
      Porção: '65g (1 unidade)',
      'Valor Energético': '115 kcal',
      Carboidratos: '20g',
      Proteínas: '1.8g',
      'Gorduras Totais': '3.5g',
    },
    allergens: ['Contém leite e derivados.', 'Não contém glúten.'],
  },
  {
    id: 35,
    name: 'Ameixa',
    category: 'picole-leite',
    subtitle: 'Picolé cremoso de Ameixa',
    description:
      'O sabor clássico da ameixa em uma versão cremosa e refrescante. Um picolé que equilibra o doce da fruta com a suavidade do leite.',
    type: 'image',
    src: '/images/picole-leite/ameixa.png',
    images: ['/images/picole-leite/ameixa.png'],
    ingredients: ['Água', 'Leite em pó', 'Açúcar', 'Polpa de ameixa', 'Estabilizantes'],
    nutrition: {
      Porção: '65g (1 unidade)',
      'Valor Energético': '105 kcal',
      Carboidratos: '19g',
      Proteínas: '1.7g',
      'Gorduras Totais': '3g',
    },
    allergens: ['Contém leite.', 'Não contém glúten.'],
  },
  {
    id: 36,
    name: 'Amendoim',
    category: 'picole-leite',
    subtitle: 'Picolé cremoso de Pasta de Amendoim',
    description:
      'Intenso e cremoso! Feito com pasta de amendoim de verdade, é a escolha perfeita para quem ama essa leguminosa. Uma explosão de sabor a cada mordida.',
    type: 'image',
    src: '/images/picole-leite/amendoim.png',
    images: ['/images/picole-leite/amendoim.png'],
    ingredients: ['Leite', 'Açúcar', 'Pasta de amendoim', 'Leite em pó', 'Estabilizantes'],
    nutrition: {
      Porção: '65g (1 unidade)',
      'Valor Energético': '140 kcal',
      Carboidratos: '15g',
      Proteínas: '4g',
      'Gorduras Totais': '7g',
    },
    allergens: ['Contém leite e amendoim.', 'Não contém glúten.'],
  },
  {
    id: 37,
    name: 'Banana',
    category: 'picole-leite',
    subtitle: 'Picolé cremoso de Banana com Leite',
    description:
      'A doçura natural da banana combinada com a cremosidade do leite. Um sabor que remete à infância, perfeito para um lanche delicioso e nutritivo.',
    type: 'image',
    src: '/images/picole-leite/banana.png',
    images: ['/images/picole-leite/banana.png'],
    ingredients: ['Leite', 'Polpa de banana', 'Açúcar', 'Leite em pó', 'Estabilizantes'],
    nutrition: {
      Porção: '65g (1 unidade)',
      'Valor Energético': '112 kcal',
      Carboidratos: '21g',
      Proteínas: '1.9g',
      'Gorduras Totais': '2.5g',
    },
    allergens: ['Contém leite.', 'Não contém glúten.'],
  },
  {
    id: 38,
    name: 'Blue Ice',
    category: 'picole-leite',
    subtitle: 'Picolé sabor Tutti-Frutti',
    description:
      'A cor vibrante e o sabor inconfundível de tutti-frutti que a criançada adora. Uma viagem divertida e refrescante a cada mordida.',
    type: 'image',
    src: '/images/picole-leite/blueice.png',
    images: ['/images/picole-leite/blueice.png'],
    ingredients: [
      'Água',
      'Açúcar',
      'Leite em pó',
      'Aroma artificial de tutti-frutti',
      'Corante azul brilhante',
      'Estabilizantes',
    ],
    nutrition: {
      Porção: '65g (1 unidade)',
      'Valor Energético': '98 kcal',
      Carboidratos: '18g',
      Proteínas: '1.2g',
      'Gorduras Totais': '2g',
    },
    allergens: ['Contém leite.', 'Não contém glúten.'],
  },
  {
    id: 42,
    name: 'Chocolate',
    category: 'picole-leite',
    subtitle: 'Picolé cremoso de Chocolate',
    description:
      'O clássico que nunca erra. Um picolé super cremoso com o sabor intenso do chocolate, perfeito para os chocólatras de plantão.',
    type: 'image',
    src: '/images/picole-leite/chocolate.png',
    images: ['/images/picole-leite/chocolate.png'],
    ingredients: [
      'Leite',
      'Açúcar',
      'Cacau em pó',
      'Leite em pó',
      'Gordura vegetal',
      'Estabilizantes',
    ],
    nutrition: {
      Porção: '65g (1 unidade)',
      'Valor Energético': '125 kcal',
      Carboidratos: '16g',
      Proteínas: '2.5g',
      'Gorduras Totais': '5.5g',
    },
    allergens: ['Contém leite e derivados.', 'Não contém glúten.'],
  },
  {
    id: 47,
    name: 'Coco',
    category: 'picole-leite',
    subtitle: 'Picolé cremoso de Coco',
    description:
      'A cremosidade do leite com pedacinhos de coco ralado. Um picolé que te transporta para uma praia tropical a cada mordida.',
    type: 'image',
    src: '/images/picole-leite/coco.png',
    images: ['/images/picole-leite/coco.png'],
    ingredients: [
      'Leite',
      'Açúcar',
      'Coco ralado',
      'Leite de coco',
      'Leite em pó',
      'Estabilizantes',
    ],
    nutrition: {
      Porção: '65g (1 unidade)',
      'Valor Energético': '130 kcal',
      Carboidratos: '17g',
      Proteínas: '2g',
      'Gorduras Totais': '6g',
    },
    allergens: ['Contém leite.', 'Não contém glúten.'],
  },
  {
    id: 48,
    name: 'Coco Queimado',
    category: 'picole-leite',
    subtitle: 'Picolé de Coco Queimado',
    description:
      'O sabor irresistível do coco queimado em uma versão gelada e cremosa. Uma sobremesa tradicional brasileira no palito.',
    type: 'image',
    src: '/images/picole-leite/cocoqueimado.png',
    images: ['/images/picole-leite/cocoqueimado.png'],
    ingredients: ['Leite', 'Açúcar', 'Coco queimado ralado', 'Leite em pó', 'Estabilizantes'],
    nutrition: {
      Porção: '65g (1 unidade)',
      'Valor Energético': '135 kcal',
      Carboidratos: '18g',
      Proteínas: '2.2g',
      'Gorduras Totais': '6.5g',
    },
    allergens: ['Contém leite.', 'Não contém glúten.'],
  },
  {
    id: 49,
    name: 'Creme',
    category: 'picole-leite',
    subtitle: 'Picolé sabor Creme',
    description:
      'A simplicidade e a sofisticação do sabor de creme baunilha. Um picolé suave, cremoso e que agrada a todos os paladares.',
    type: 'image',
    src: '/images/picole-leite/creme.png',
    images: ['/images/picole-leite/creme.png'],
    ingredients: ['Leite', 'Creme de leite', 'Açúcar', 'Extrato de baunilha', 'Estabilizantes'],
    nutrition: {
      Porção: '65g (1 unidade)',
      'Valor Energético': '120 kcal',
      Carboidratos: '15g',
      Proteínas: '2g',
      'Gorduras Totais': '5g',
    },
    allergens: ['Contém leite e derivados.', 'Não contém glúten.'],
  },
  {
    id: 50,
    name: 'Cupuaçu',
    category: 'picole-leite',
    subtitle: 'Picolé cremoso de Cupuaçu',
    description:
      'O sabor exótico e inconfundível do cupuaçu da Amazônia em um picolé cremoso. Uma experiência única que combina acidez e doçura na medida certa.',
    type: 'image',
    src: '/images/picole-leite/cupuacu.png',
    images: ['/images/picole-leite/cupuacu.png'],
    ingredients: ['Polpa de cupuaçu', 'Leite', 'Açúcar', 'Leite em pó', 'Estabilizantes'],
    nutrition: {
      Porção: '65g (1 unidade)',
      'Valor Energético': '118 kcal',
      Carboidratos: '20g',
      Proteínas: '1.6g',
      'Gorduras Totais': '3.8g',
    },
    allergens: ['Contém leite.', 'Não contém glúten.'],
  },
  {
    id: 53,
    name: 'Goiaba',
    category: 'picole-leite',
    subtitle: 'Picolé cremoso de Goiaba',
    description:
      'O doce sabor da goiaba madura em uma versão cremosa e refrescante. Uma delícia que lembra um smoothie de fruta no palito.',
    type: 'image',
    src: '/images/picole-leite/goiaba.png',
    images: ['/images/picole-leite/goiaba.png'],
    ingredients: ['Leite', 'Polpa de goiaba', 'Açúcar', 'Leite em pó', 'Estabilizantes'],
    nutrition: {
      Porção: '65g (1 unidade)',
      'Valor Energético': '108 kcal',
      Carboidratos: '20g',
      Proteínas: '1.5g',
      'Gorduras Totais': '2.5g',
    },
    allergens: ['Contém leite.', 'Não contém glúten.'],
  },
  {
    id: 54,
    name: 'Iogurte com Morango',
    category: 'picole-leite',
    subtitle: 'Picolé de Iogurte com Calda de Morango',
    description:
      'A leveza do iogurte combinada com uma deliciosa calda de morango. Um picolé cremoso, refrescante e com um toque azedinho.',
    type: 'image',
    src: '/images/picole-leite/iogurtemorango.png',
    images: ['/images/picole-leite/iogurtemorango.png'],
    ingredients: [
      'Iogurte natural',
      'Leite',
      'Açúcar',
      'Calda de morango',
      'Leite em pó',
      'Estabilizantes',
    ],
    nutrition: {
      Porção: '65g (1 unidade)',
      'Valor Energético': '112 kcal',
      Carboidratos: '19g',
      Proteínas: '2.5g',
      'Gorduras Totais': '3g',
    },
    allergens: ['Contém leite e derivados.', 'Não contém glúten.'],
  },
  {
    id: 56,
    name: 'Leite Condensado',
    category: 'picole-leite',
    subtitle: 'Picolé cremoso de Leite Condensado',
    description:
      'A doçura e a cremosidade inconfundíveis do leite condensado. Uma sobremesa gelada, simples e absolutamente deliciosa.',
    type: 'image',
    src: '/images/picole-leite/leitecondensado.png',
    images: ['/images/picole-leite/leitecondensado.png'],
    ingredients: ['Leite condensado', 'Leite', 'Creme de leite', 'Açúcar', 'Estabilizantes'],
    nutrition: {
      Porção: '65g (1 unidade)',
      'Valor Energético': '130 kcal',
      Carboidratos: '22g',
      Proteínas: '2.1g',
      'Gorduras Totais': '4g',
    },
    allergens: ['Contém leite e derivados.', 'Não contém glúten.'],
  },
  {
    id: 58,
    name: 'Limão Suíço',
    category: 'picole-leite',
    subtitle: 'Picolé cremoso de Limão com Leite',
    description:
      'A combinação perfeita do azedinho do limão com a cremosidade do leite condensado. Refrescante e cremoso na medida certa.',
    type: 'image',
    src: '/images/picole-leite/limaosuico.png',
    images: ['/images/picole-leite/limaosuico.png'],
    ingredients: ['Leite condensado', 'Suco de limão', 'Água', 'Leite em pó', 'Estabilizantes'],
    nutrition: {
      Porção: '65g (1 unidade)',
      'Valor Energético': '115 kcal',
      Carboidratos: '21g',
      Proteínas: '1.8g',
      'Gorduras Totais': '3.2g',
    },
    allergens: ['Contém leite e derivados.', 'Não contém glúten.'],
  },
  {
    id: 60,
    name: 'Milho Verde',
    category: 'picole-leite',
    subtitle: 'Picolé cremoso de Milho Verde',
    description:
      'O autêntico sabor do milho verde em um picolé incrivelmente cremoso. Uma delícia que remete às festas juninas e à culinária brasileira.',
    type: 'image',
    src: '/images/picole-leite/milho.png',
    images: ['/images/picole-leite/milho.png'],
    ingredients: ['Leite', 'Milho verde', 'Açúcar', 'Leite condensado', 'Estabilizantes'],
    nutrition: {
      Porção: '65g (1 unidade)',
      'Valor Energético': '122 kcal',
      Carboidratos: '20g',
      Proteínas: '2.5g',
      'Gorduras Totais': '3.5g',
    },
    allergens: ['Contém leite e derivados.', 'Não contém glúten.'],
  },
  {
    id: 61,
    name: 'Morango',
    category: 'picole-leite',
    subtitle: 'Picolé cremoso de Morango',
    description:
      'O sabor clássico e amado do morango em uma versão super cremosa. Feito com polpa da fruta, é doce na medida certa.',
    type: 'image',
    src: '/images/picole-leite/morangoleite.png',
    images: ['/images/picole-leite/morangoleite.png'],
    ingredients: ['Leite', 'Polpa de morango', 'Açúcar', 'Leite em pó', 'Estabilizantes'],
    nutrition: {
      Porção: '65g (1 unidade)',
      'Valor Energético': '105 kcal',
      Carboidratos: '19g',
      Proteínas: '1.5g',
      'Gorduras Totais': '2.8g',
    },
    allergens: ['Contém leite.', 'Não contém glúten.'],
  },

  // PICOLÉ DE FRUTA
  {
    id: 65,
    name: 'Abacaxi',
    category: 'picole-fruta',
    subtitle: 'Picolé refrescante de Abacaxi',
    description:
      'Puro frescor tropical! Feito com suco natural de abacaxi, nosso picolé de fruta é a pedida certa para matar o calor com muito sabor e leveza.',
    type: 'image',
    src: '/images/picole-fruta/abacaxi.png',
    images: ['/images/picole-fruta/abacaxi.png'],
    ingredients: ['Água', 'Açúcar', 'Polpa de abacaxi', 'Ácido cítrico', 'Estabilizantes'],
    nutrition: {
      Porção: '60g (1 unidade)',
      'Valor Energético': '80 kcal',
      Carboidratos: '19g',
      Proteínas: '0.5g',
      'Gorduras Totais': '0g',
    },
    allergens: ['Não contém leite.', 'Não contém glúten.'],
  },

  // --- ITUZINHO ---
  {
    id: 87,
    name: 'Leite Condensado',
    category: 'ituzinho',
    subtitle: 'Ituzinho de Leite Condensado',
    description:
      'A doçura irresistível do leite condensado em um formato mini, perfeito para uma sobremesa rápida e deliciosa.',
    type: 'image',
    src: '/images/picole-ituzinho/ituleitecondensado.png',
    images: ['/images/picole-ituzinho/ituleitecondensado.png'],
    ingredients: ['Leite condensado', 'Leite', 'Creme de leite', 'Estabilizantes'],
    nutrition: {
      Porção: '45g (1 unidade)',
      'Valor Energético': '90 kcal',
      Carboidratos: '15g',
      Proteínas: '1.5g',
      'Gorduras Totais': '2.5g',
    },
    allergens: ['Contém leite e derivados.', 'Não contém glúten.'],
  },
  {
    id: 89,
    name: 'Maracujá',
    category: 'ituzinho',
    subtitle: 'Ituzinho de Maracujá',
    description:
      'O sabor tropical e azedinho do maracujá em uma versão mini e cremosa. Um picolé para refrescar seu dia em pequenas porções.',
    type: 'image',
    src: '/images/picole-ituzinho/itumaracuja.png',
    images: ['/images/picole-ituzinho/itumaracuja.png'],
    ingredients: ['Leite', 'Polpa de maracujá', 'Açúcar', 'Leite em pó', 'Estabilizantes'],
    nutrition: {
      Porção: '45g (1 unidade)',
      'Valor Energético': '80 kcal',
      Carboidratos: '14g',
      Proteínas: '1.2g',
      'Gorduras Totais': '2g',
    },
    allergens: ['Contém leite.', 'Não contém glúten.'],
  },

  // --- SKIMO ---
  {
    id: 92,
    name: 'Brigadeiro',
    category: 'skimo',
    subtitle: 'Picolé Brigadeiro com cobertura de Chocolate',
    description:
      'Uma casquinha crocante de chocolate que esconde um recheio incrivelmente cremoso de brigadeiro. A sobremesa perfeita no palito!',
    type: 'image',
    src: '/images/picole-skimo/brigadeiro.png',
    images: ['/images/picole-skimo/brigadeiro.png'],
    ingredients: [
      'Leite condensado',
      'Creme de leite',
      'Chocolate em pó',
      'Cobertura de chocolate (gordura vegetal, açúcar, cacau)',
      'Estabilizantes',
    ],
    nutrition: {
      Porção: '70g (1 unidade)',
      'Valor Energético': '210 kcal',
      Carboidratos: '25g',
      Proteínas: '3g',
      'Gorduras Totais': '11g',
    },
    allergens: ['Contém leite e derivados.', 'Contém derivados de soja.'],
  },
  {
    id: 94,
    name: 'Tentação',
    category: 'skimo',
    subtitle: 'Picolé de Morango com cobertura de Chocolate',
    description:
      'A combinação perfeita de um recheio cremoso de morango envolvido por uma casquinha crocante de chocolate. Uma verdadeira tentação!',
    type: 'image',
    src: '/images/picole-skimo/tentacao.png',
    images: ['/images/picole-skimo/tentacao.png'],
    ingredients: [
      'Leite',
      'Polpa de morango',
      'Açúcar',
      'Cobertura de chocolate',
      'Estabilizantes',
    ],
    nutrition: {
      Porção: '70g (1 unidade)',
      'Valor Energético': '195 kcal',
      Carboidratos: '23g',
      Proteínas: '2.5g',
      'Gorduras Totais': '10g',
    },
    allergens: ['Contém leite e derivados.', 'Contém derivados de soja.', 'Não contém glúten.'],
  },
])
